export const CountryCode = [
  { code: "en", language: "English" }, // English
  { code: "es", language: "Spanish" }, // Spanish
  { code: "fr", language: "French" }, // French
  { code: "de", language: "German" }, // German
  { code: "zh", language: "Chinese" }, // Chinese
  { code: "hi", language: "Hindi" }, // Hindi
  { code: "ar", language: "Arabic" }, // Arabic
  { code: "bn", language: "Bengali" }, // Bengali
  { code: "pt", language: "Portuguese" }, // Portuguese
  { code: "ru", language: "Russian" }, // Russian
  { code: "ja", language: "Japanese" }, // Japanese
  { code: "pa", language: "Punjabi" }, // Punjabi
  { code: "ms", language: "Malay" }, // Malay
  { code: "te", language: "Telugu" }, // Telugu
  { code: "ta", language: "Tamil" }, // Tamil
  { code: "ur", language: "Urdu" }, // Urdu
  { code: "it", language: "Italian" }, // Italian
  { code: "tr", language: "Turkish" }, // Turkish
  { code: "ko", language: "Korean" }, // Korean
  { code: "vi", language: "Vietnamese" }, // Vietnamese
  { code: "pl", language: "Polish" }, // Polish
  { code: "fa", language: "Persian" }, // Persian
  { code: "ro", language: "Romanian" }, // Romanian
  { code: "nl", language: "Dutch" }, // Dutch
  { code: "hu", language: "Hungarian" }, // Hungarian
  { code: "sv", language: "Swedish" }, // Swedish
  { code: "fi", language: "Finnish" }, // Finnish
  { code: "el", language: "Greek" }, // Greek
  { code: "cs", language: "Czech" }, // Czech
  { code: "th", language: "Thai" }, // Thai
  { code: "he", language: "Hebrew" }, // Hebrew
  { code: "id", language: "Indonesian" }, // Indonesian
  { code: "no", language: "Norwegian" }, // Norwegian
  { code: "da", language: "Danish" }, // Danish
  { code: "uk", language: "Ukrainian" }, // Ukrainian
  { code: "sr", language: "Serbian" }, // Serbian
  { code: "bg", language: "Bulgarian" }, // Bulgarian
  { code: "hr", language: "Croatian" }, // Croatian
  { code: "sk", language: "Slovak" }, // Slovak
  { code: "lt", language: "Lithuanian" }, // Lithuanian
  { code: "sl", language: "Slovenian" }, // Slovenian
  { code: "et", language: "Estonian" }, // Estonian
  { code: "lv", language: "Latvian" }, // Latvian
  { code: "sq", language: "Albanian" }, // Albanian
  { code: "hy", language: "Armenian" }, // Armenian
  { code: "ka", language: "Georgian" }, // Georgian
  { code: "sw", language: "Swahili" }, // Swahili
  { code: "fi", language: "Finnish" }, // Finnish
  { code: "ta", language: "Tamil" }, // Tamil
  { code: "mr", language: "Marathi" }, // Marathi
  { code: "kn", language: "Kannada" }, // Kannada
  { code: "gu", language: "Gujarati" }, // Gujarati
  { code: "pa", language: "Punjabi" }, // Punjabi
  { code: "or", language: "Oriya" }, // Oriya
  { code: "ml", language: "Malayalam" }, // Malayalam
  { code: "sd", language: "Sindhi" }, // Sindhi
  { code: "ne", language: "Nepali" }, // Nepali
  { code: "si", language: "Sinhala" }, // Sinhala
  { code: "kk", language: "Kazakh" }, // Kazakh
  { code: "uz", language: "Uzbek" }, // Uzbek
  { code: "ky", language: "Kyrgyz" }, // Kyrgyz
  { code: "tg", language: "Tajik" }, // Tajik
  { code: "tk", language: "Turkmen" }, // Turkmen
  { code: "mn", language: "Mongolian" }, // Mongolian
  { code: "bo", language: "Tibetan" }, // Tibetan
  { code: "my", language: "Burmese" }, // Burmese
  { code: "lo", language: "Lao" }, // Lao
  { code: "km", language: "Khmer" }, // Khmer
  { code: "th", language: "Thai" }, // Thai
  { code: "vi", language: "Vietnamese" }, // Vietnamese
  { code: "id", language: "Indonesian" }, // Indonesian
  { code: "tl", language: "Tagalog" }, // Tagalog
  { code: "ms", language: "Malay" }, // Malay
  { code: "jv", language: "Javanese" }, // Javanese
  { code: "su", language: "Sundanese" }, // Sundanese
  { code: "mi", language: "Maori" }, // Maori
  { code: "haw", language: "Hawaiian" }, // Hawaiian
  { code: "sm", language: "Samoan" }, // Samoan
  { code: "to", language: "Tongan" }, // Tongan
  { code: "tpi", language: "Tok Pisin" }, // Tok Pisin
  { code: "fj", language: "Fijian" }, // Fijian
  { code: "sm", language: "Samoan" }, // Samoan
  { code: "chr", language: "Cherokee" }, // Cherokee
  { code: "tn", language: "Setswana" }, // Setswana
  { code: "st", language: "Southern Sotho" }, // Southern Sotho
  { code: "ts", language: "Tsonga" }, // Tsonga
  { code: "nso", language: "Northern Sotho" }, // Northern Sotho
  { code: "xh", language: "Xhosa" }, // Xhosa
  { code: "zu", language: "Zulu" }, // Zulu
  { code: "ss", language: "Swati" }, // Swati
  { code: "ve", language: "Venda" }, // Venda
  { code: "af", language: "Afrikaans" }, // Afrikaans
  { code: "nr", language: "Ndebele" }, // Ndebele
  { code: "rw", language: "Kinyarwanda" }, // Kinyarwanda
  { code: "sn", language: "Shona" }, // Shona
  { code: "bm", language: "Bambara" }, // Bambara
  { code: "lg", language: "Luganda" }, // Luganda
  { code: "ak", language: "Akan" }, // Akan
  { code: "tw", language: "Twi" }, // Twi
  { code: "ha", language: "Hausa" }, // Hausa
  { code: "yo", language: "Yoruba" }, // Yoruba
  { code: "ig", language: "Igbo" }, // Igbo
  { code: "ff", language: "Fula" }, // Fula
  { code: "ki", language: "Kikuyu" }, // Kikuyu
  { code: "ny", language: "Chichewa" }, // Chichewa
  { code: "sw", language: "Swahili" }, // Swahili
  { code: "ee", language: "Ewe" }, // Ewe
];
